### ISSUE TITLE
Hi., when i installed rundeck by using this steps couldn't get libext file

### ISSUE THREAD

**Issue by Thirumalairaja-K** [1DevOps2/Rundeck#1]

**Comment by anaskhandevops** [comment]
@Thirumalairaja-K To provide you with the most accurate help, I'll need a bit more information about the problem you're encountering. Specifically, could you please clarify what you mean by "couldn't get libext file #1"? Additionally, if you could provide the steps you followed and any error messages you received,

**Comment by anaskhandevops** [comment]
.
